
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-v1-project
  failurePolicy: Fail
  name: vproject.kb.io
  rules:
  - apiGroups:
    - project.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - projects
  sideEffects: None
