
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
  selector:
    control-plane: controller-manager
  type: ClusterIP
